name: Build Tauri app for macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Шаг 3: Установка Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Шаг 4: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 5: Сборка Tauri приложения
      - name: Build Tauri app
        run: npm run tauri build 


      # Шаг 6: Подпись и сброс параметров
      - name: Sign the app (disable quarantine)
        run: |
          chmod -R a+x "src-tauri/target/release/bundle/macos/excel-tauri.app"
          xattr -rd com.apple.quarantine "src-tauri/target/release/bundle/macos/excel-tauri.app"
          codesign --force --deep --sign - --options runtime "src-tauri/target/release/bundle/macos/excel-tauri.app"

      # Шаг 7: Сохранение собранного приложения как артефакта
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-macos
          path: src-tauri/target/release/bundle/
